### ISSUE TITLE
update SDK to 12.0.0

### ISSUE THREAD

**Issue by marc0olo** [YinkaEnoch/aepp-boilerplate-angular#1]
Hey @YinkaEnoch,

today we release the new SDK version. Would be great to have the boilerplate updated. We're also refering to it on the recently published new website in the build section.

I know you're still waiting for the bounty payout. I asked about that issue today and I hope it's being solved soon. Sorry for the huge delay, but you will definitely receive it!

Best regards
Marco

**Comment by marc0olo** [comment]
Hey @YinkaEnoch, it has been a while 😅 

meanhwile SDK v12.0.0 with TypeScript support has been released. Would be cool if you could update it. We're happy to support in case of questions.

**Comment by YinkaEnoch** [comment]
Noted.

**Comment by marc0olo** [comment]
cool :)

be aware of the breaking changes! https://aeternity.com/aepp-sdk-js/v12.0.0/guides/migration/12.0.0
